export type TransportSheet = {
  id: string | null;
  organizationId: string;
  transportServiceId: string;
  sheetNumber: number | null;
  reportDate: string;
  destinationName: string;
  destinationAddress: string;
  destinationCity: string;
  destinationProvince: string;
  destinationNotes: string;
  clientFiscalCode: string;
  clientFirstName: string;
  clientLastName: string;
  clientFullName: string;
  clientPhone: string;
  clientAddress: string;
  clientCity: string;
  clientProvince: string;
  clientAslNumber: string;
  clientAslMunicipality: string;
  clientNotes: string;
  vehiclePlate: string;
  startTime: string | null;
  endTime: string | null;
  kmDeparture: number | null;
  kmArrival: number | null;
  notes: string;
  createdAt: string;
  volunteerIds: string[];
};

export type TransportSheetDto = {
  id?: string | null;
  organizationId?: string | null;
  transportServiceId?: string | null;
  sheetNumber?: number;
  reportDate?: string | null;
  destinationName?: string | null;
  destinationAddress?: string | null;
  destinationCity?: string | null;
  destinationProvince?: string | null;
  destinationNotes?: string | null;
  clientFiscalCode?: string | null;
  clientFirstName?: string | null;
  clientLastName?: string | null;
  clientFullName?: string | null;
  clientPhone?: string | null;
  clientAddress?: string | null;
  clientCity?: string | null;
  clientProvince?: string | null;
  clientAslNumber?: string | null;
  clientAslMunicipality?: string | null;
  clientNotes?: string | null;
  vehiclePlate?: string | null;
  startTime?: string | null;
  endTime?: string | null;
  kmDeparture?: number | null;
  kmArrival?: number | null;
  notes?: string | null;
  createdAt?: string | null;
  volunteerIds?: string[] | null;
};

export type TransportSheetListItem = {
  id: string;
  organizationId: string;
  transportServiceId: string;
  sheetNumber: number;
  reportDate: string;
  destinationName: string;
  clientFiscalCode: string;
  clientFullName: string;
  vehiclePlate: string;
  startTime: string | null;
  endTime: string | null;
  kmDeparture: number | null;
  kmArrival: number | null;
  createdAt: string;
};

export type TransportSheetListItemDto = {
  id?: string | null;
  organizationId?: string | null;
  transportServiceId?: string | null;
  sheetNumber?: number;
  reportDate?: string | null;
  destinationName?: string | null;
  clientFiscalCode?: string | null;
  clientFullName?: string | null;
  vehiclePlate?: string | null;
  startTime?: string | null;
  endTime?: string | null;
  kmDeparture?: number | null;
  kmArrival?: number | null;
  createdAt?: string | null;
};

export type TransportSheetPagedResultDto = {
  items?: TransportSheetListItemDto[] | null;
  pageIndex?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
  hasPreviousPage?: boolean;
  hasNextPage?: boolean;
};

export type TransportSheetFormData = {
  sheetNumber?: number;
  organizationId: string;
  reportDate: string;
  destinationName: string;
  destinationAddress: string;
  destinationCity: string;
  destinationProvince: string;
  destinationNotes: string;
  clientFiscalCode: string;
  clientFirstName: string;
  clientLastName: string;
  clientPhone: string;
  clientAddress: string;
  clientCity: string;
  clientProvince: string;
  clientAslNumber: string;
  clientAslMunicipality: string;
  clientNotes: string;
  vehiclePlate: string;
  startTime: string;
  endTime: string;
  kmDeparture: string;
  kmArrival: string;
  notes: string;
  volunteerIds: string[];
  volunteerDisplayNames?: string[];
};

export type TransportSheetUpsertRequestDto = {
  organizationId: string | null;
  reportDate: string | null;
  destinationName: string | null;
  destinationAddress: string | null;
  destinationCity: string | null;
  destinationProvince: string | null;
  destinationNotes: string | null;
  clientFiscalCode: string | null;
  clientFirstName: string | null;
  clientLastName: string | null;
  clientPhone: string | null;
  clientAddress: string | null;
  clientCity: string | null;
  clientProvince: string | null;
  clientAslNumber: string | null;
  clientAslMunicipality: string | null;
  clientNotes: string | null;
  vehiclePlate: string | null;
  startTime: string | null;
  endTime: string | null;
  kmDeparture: number | null;
  kmArrival: number | null;
  notes: string | null;
  volunteerIds: string[] | null;
};
